services:
  minecraft:
    build: .
    container_name: dahole-purpur-desert
    restart: unless-stopped
    environment:
      - EULA=true
    ports:
      - "3403:25565"
      - "3402:3402/udp"
      - "3404:3404"
    volumes:
      - ./:/opt/minecraft/server
      - ./data:/data
    tty: true
    stdin_open: true
    mem_limit: 12.5G

